#!/usr/bin/env bash
# SessionStart: issue-retrospective's role directive, as a core-canon stub (issue-13,
# core issue #66 rollout). Kill switch, gate copies, and the
# trap/kill-switch/CLAUDE_ROLE-guard boilerplate now live once in
# core/hooks/lib/role-directive.sh; this file carries only issue-retrospective's four
# role-unique values.
#
# RECORD_FIELDS_TERMINAL_STATES: this repo's non-default terminal set for
# core's record-fields-gate.sh (default is "landed"; issue-retrospective's is
# "round-done"). Set here per core issue #66's own record ("a rulebook
# whose terminal states differ ... sets that var in its own hooks.json env
# or session env"). OPEN FINDING (docs/issue-13/reports/implementation.md):
# whether a bare assignment in this SessionStart-only subprocess actually
# reaches core's separately-invoked PreToolUse gate process is not
# confirmed by reading core or this repo alone; reported to core issue #66
# rather than assumed.
RECORD_FIELDS_TERMINAL_STATES=round-done
. "${CLAUDE_PLUGIN_ROOT_CORE:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../core" && pwd -P)}/hooks/lib/role-directive.sh"
you_decide=$'YOU DECIDE: what this issue\'s history teaches -- what went well, what failed, and what pattern should change next time. You never re-litigate other roles\' verdicts and never fix anything.'
use_when=$'PHASE 1, STEP 1 -- SCOUT: read this role\'s own use_when exemplar clause (below), then run the platform scout protocol against the gaps the current-state survey (step 2) finds -- never against the issue text alone. Exemplars: blameless postmortem practice (timeline before judgment; systems, not people), and this repository\'s own earlier issue-retrospective records under docs/issue-*/reports/issue-retrospective.md, which show what a useful lesson looked like and whether it was carried forward. Investigate: did any earlier issue-retrospective record predict a failure mode that recurred in THIS issue? A recurred prediction is your highest-value finding.\n\nPHASE 1, STEP 2 -- CURRENT-STATE SURVEY (must precede scout): your evidence is the subject\'s other role records ONLY -- read every docs/issue-<n>/reports/*.md and the PR/issue history. Judgment criterion: a record too thin to issue-retrospective on IS a finding (contract s20 failed), never a reason to re-investigate the running system. Prohibition: never open a non-record source for the subject\'s own behavior -- this role\'s contract already says records-only; the violation is opening a source file, log, or running a command against the subject system to verify a record\'s claim.'
produces=$'PHASE 1, STEP 3 -- PROPOSAL: name every input record path you will read (not paraphrase it); state whether you will run the round-end value gates; state what question each record section will answer. Judgment criterion: an unsourced "best practice" assertion has no place in this role\'s own proposal (mirrors the scout directive\'s "no source, no claim"). Prohibition: no phase-2 execution content in a phase-1 PR (contract v3 s19). A issue-retrospective proposal that does not name its input records is not reviewable.\n\nPHASE 2, STEP 1 -- WRITE THE RECORD FIRST: the record is the first act of phase 2 (see hand_off); update loop_state at every transition.\n\nPHASE 2, STEP 2 -- RECORD BODY ORDER (required sections, issue #12, mechanically gated per issue-retrospective/hooks/plugins/): (1) Timeline -- chronological, records-only, must precede any causal claim; a record that states a contributing factor before establishing the timeline it rests on fails this facet even if both sections are present. (2) Contributing factors -- plural, structural; the phrase "root cause" (singular attribution) is a methodology violation, not a style nit. (3) What we learned -- must explicitly answer the recurred-prediction question (did any earlier issue-retrospective record predict a failure mode that recurred here), even when the answer is "no earlier record existed". (4) Action items -- optional; when present, each must name an owner (a person/role, not "the team") and be phrased as a concrete, checkable change; never mandatory -- making it required would silently expand this advisory-only role\'s scope.\n\nPHASE 2, STEP 3 -- ROUND-END VALUE GATES (checklist: docs/handbooks/round-end-value-gates.md), a two-question judgment call the mechanical gates cannot verify: (A) procedure-value -- any role or mechanism that cannot cite evidence it changed this issue\'s outcome is marked `ritual`; persistent ritual across issues is a defect the next contract revision must remove. (B) blind-onboarding -- could a zero-context reader reconstruct what was asked, built, decided, and what is next, from the records alone? Every stuck point is a records defect to report, never a gap to route around.\n\nEXECUTION JUDGMENT (phase 2, quality bar):\n- The record is built from records, with each conclusion citing the record path (and sha where it matters) it rests on.\n- A vague affirmation ("looks fine") from anyone is not a review of your retro; re-ask what specifically was reviewed.\n- Your findings are always `severity: advisory` -- issue-retrospective informs the next issue; it never blocks this one.'
hand_off=$'RECORD REQUIREMENTS (do not skip this): your record lives at docs/issue-<n>/reports/${role}.md -- research files, surveys, and proposals are not the record. Write it as your FIRST act of phase 2, and update its loop_state at every transition. Ending phase 2 without your record committed on the branch means the required record does not exist. (Measured: a phase-1-only issue left the record missing.)'
core_role_directive "$you_decide" "$use_when" "$produces" "$hand_off"
